// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "3fc1a976-00fb-437f-8dac-386e5a7471a9";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBackwardChange();
void onCameraChange();
void onForwardChange();
void onLeftChange();
void onRightChange();

bool backward;
bool camera;
bool forward;
bool left;
bool right;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(backward, READWRITE, ON_CHANGE, onBackwardChange);
  ArduinoCloud.addProperty(camera, READWRITE, ON_CHANGE, onCameraChange);
  ArduinoCloud.addProperty(forward, READWRITE, ON_CHANGE, onForwardChange);
  ArduinoCloud.addProperty(left, READWRITE, ON_CHANGE, onLeftChange);
  ArduinoCloud.addProperty(right, READWRITE, ON_CHANGE, onRightChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
